name: SenescenceKG
channels:
  - pytorch
  - bioconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8.10
  - pandas
  - numpy
  - tensorflow=2.8.0
  - scikit-learn
  - optuna
  - pytorch
  - mygene
  - owlready2
  - numba
  - umap-learn
  - matplotlib
  - jupyter
  - pip
  - pip:
    - tensorflow-gpu
    - pykeen
    - neo4j
